repos:
    - repo: https://github.com/psf/black
      rev: 19.10b0
      hooks:
        - id: black
    - repo: https://github.com/PyCQA/pylint
      rev: pylint-2.4.4
      hooks:
        - id: pylint
    - repo: local
      hooks:
        - id: pipenv to requirements
          name: pipenv to requirements
          entry: pipenv run pipenv_to_requirements
          language: system
          always_run: true
          pass_filenames: false